# Generated by Django 2.0 on 2020-04-18 08:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('poster', models.FileField(max_length=256, upload_to='')),
                ('duration', models.CharField(max_length=256)),
                ('release_time', models.CharField(max_length=256)),
                ('intro', models.TextField()),
                ('director', models.CharField(max_length=256)),
                ('writers', models.CharField(max_length=256)),
                ('actors', models.CharField(max_length=512)),
                ('genre', models.ManyToManyField(to='movie.Genre')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='Movie_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
            options={
                'db_table': 'Movie_rating',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rating_movies', models.ManyToManyField(through='movie.Movie_rating', to='movie.Movie')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='movie_rating',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.User'),
        ),
    ]
